samples:
  P32269_1001:
    R1_PATH: /Users/marek/human/P32269_1001_short/P32269_1001_R1_001.fastq.gz
    R2_PATH: /Users/marek/human/P32269_1001_short/P32269_1001_R2_001.fastq.gz
    R3_PATH: /Users/marek/human/P32269_1001_short/P32269_1001_R3_001.fastq.gz
    I1_PATH: /Users/marek/human/P32269_1001_short/P32269_1001_I1_001.fastq.gz
    modality: H3K27ac
    age: w9.5
    region: cortex
    species: human

general:
  tempdir: /Users/marek/tmp
  outdir: /Users/marek/human/out_test
  bwa_index: /Users/marek/references/hg38/bwa/hg38.fa.gz